import { ValidationError } from "./error";

export const SLUG_PATTERN = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
const EMAIL_PATTERN = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

export const MAX_NAME_LENGTH = 120;
export const MAX_SLUG_LENGTH = 64;
export const MAX_EMAIL_LENGTH = 254;
// GoTrue's default minimum; long enough that a temporary admin
// password generated by the provisioning flow is not guessable.
export const MIN_PASSWORD_LENGTH = 12;

/**
 * Derives a URL-safe slug from free text: lowercase, anything that is
 * not a letter or digit becomes a single hyphen, leading/trailing
 * hyphens are dropped. Never returns a slug that would fail
 * SLUG_PATTERN — that is what validateProvisioningInput is for.
 */
export function slugify(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function requireName(value: unknown): string {
  if (typeof value !== "string" || value.trim().length === 0) {
    throw new ValidationError("Company name is required.");
  }
  const name = value.trim();
  if (name.length < 2) {
    throw new ValidationError("Company name is too short.");
  }
  if (name.length > MAX_NAME_LENGTH) {
    throw new ValidationError(`Company name must be at most ${MAX_NAME_LENGTH} characters.`);
  }
  return name;
}

function requireSlug(value: unknown, name: string): string {
  const raw = typeof value === "string" ? value.trim().toLowerCase() : "";
  const slug = raw.length > 0 ? raw : slugify(name);

  if (slug.length === 0) {
    throw new ValidationError("Could not derive a slug from that name — enter one explicitly.");
  }
  if (slug.length < 2 || slug.length > MAX_SLUG_LENGTH) {
    throw new ValidationError(`Slug must be between 2 and ${MAX_SLUG_LENGTH} characters.`);
  }
  if (!SLUG_PATTERN.test(slug)) {
    throw new ValidationError(
      "Slug may only contain lowercase letters, digits and single hyphens."
    );
  }
  return slug;
}

function requireEmail(value: unknown): string {
  if (typeof value !== "string" || value.trim().length === 0) {
    throw new ValidationError("Admin email is required.");
  }
  const email = value.trim().toLowerCase();
  if (email.length > MAX_EMAIL_LENGTH) {
    throw new ValidationError("Admin email is too long.");
  }
  if (!EMAIL_PATTERN.test(email)) {
    throw new ValidationError("Admin email must be a valid email address.");
  }
  return email;
}

export interface ProvisioningInput {
  name: string;
  slug: string;
  adminEmail: string;
}

/**
 * Server-side validation for organization provisioning. The browser's
 * `required` attributes are a convenience, not a control: every value
 * is checked again here, and the database function in 0015 validates
 * the name and slug a third time.
 */
export function validateProvisioningInput(input: unknown): ProvisioningInput {
  if (typeof input !== "object" || input === null) {
    throw new ValidationError("Invalid organization payload.");
  }
  const value = input as Record<string, unknown>;

  const name = requireName(value.name);
  return {
    name,
    slug: requireSlug(value.slug, name),
    adminEmail: requireEmail(value.adminEmail),
  };
}
